#!/usr/bin/env python3
"""schemas/*.schema.json から Pydantic v2 モデル(models/)を生成する。

正本はJSON Schema(ADR-0002)。Pydanticモデルは単方向生成の生成物としてコミットし、
--check でCIが「再生成→diff無し」を検証する(乖離防止)。

使用例:
    uv run python scripts/gen_models.py          # models/ を再生成
    uv run python scripts/gen_models.py --check  # 差分検証のみ(CI用、書き込まない)
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from pathlib import Path

_SCHEMA_SUFFIX = ".schema.json"
_REPO_ROOT = Path(__file__).resolve().parent.parent


class ModelGenerationError(Exception):
    """datamodel-code-generator の実行が失敗した(入力schema・stderrを文脈に含む)。"""


def module_name_for(schema_filename: str) -> str:
    """schemaファイル名を生成モジュール名へ写す(例: artifact-base.schema.json → artifact_base.py)。

    Raises:
        ValueError: 命名規約(`<artifact-type>.schema.json`、schemas/README.md)に合わない。
    """
    if not schema_filename.endswith(_SCHEMA_SUFFIX):
        raise ValueError(f"schemaファイル名は *{_SCHEMA_SUFFIX} であること: {schema_filename}")
    stem = schema_filename.removesuffix(_SCHEMA_SUFFIX)
    return f"{stem.replace('-', '_')}.py"


def collect_schema_files(schemas_dir: Path) -> tuple[Path, ...]:
    """schemas/ から *.schema.json を名前順で集める(決定的)。

    Raises:
        FileNotFoundError: ディレクトリ欠落・schemaファイル0件。
    """
    if not schemas_dir.is_dir():
        raise FileNotFoundError(f"schemaディレクトリが存在しない: {schemas_dir}")
    files = sorted(schemas_dir.glob(f"*{_SCHEMA_SUFFIX}"))
    if not files:
        raise FileNotFoundError(f"schemaファイル(*{_SCHEMA_SUFFIX})が1件も無い: {schemas_dir}")
    return tuple(files)


def _file_header(schema_filename: str) -> str:
    return (
        f"# generated by scripts/gen_models.py from schemas/{schema_filename} — do not edit\n"
        "# 正本はJSON Schema(ADR-0002)。再生成: uv run python scripts/gen_models.py"
    )


def _generator_cmd(schema_path: Path, output_path: Path) -> tuple[str, ...]:
    return (
        sys.executable,
        "-m",
        "datamodel_code_generator",
        "--input",
        str(schema_path),
        "--input-file-type",
        "jsonschema",
        "--output",
        str(output_path),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.12",
        # CI diff検証の前提となる決定的出力のため、timestampを消しformatterを固定する
        "--disable-timestamp",
        "--formatters",
        "black",
        "isort",
        # con*型ではなくFieldの制約で表現する(Pydantic v2の推奨スタイル)
        "--field-constraints",
        "--custom-file-header",
        _file_header(schema_path.name),
    )


def _generate_model(schema_path: Path, output_path: Path) -> None:
    result = subprocess.run(
        _generator_cmd(schema_path, output_path),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise ModelGenerationError(
            f"生成失敗: {schema_path.name} (exit {result.returncode})\n{result.stderr.strip()}"
        )


def _module_mapping(schema_files: tuple[Path, ...]) -> dict[str, Path]:
    """モジュール名→schemaファイルの写像を作る。衝突は黙った上書きになるためfail-fastする。

    Raises:
        ValueError: 複数schemaが同一モジュール名に写る(例: a-b と a_b はともに a_b.py)。
    """
    mapping: dict[str, Path] = {}
    for schema_path in schema_files:
        module = module_name_for(schema_path.name)
        if module in mapping:
            raise ValueError(
                f"モジュール名衝突: {mapping[module].name} と {schema_path.name} が"
                f"同じ {module} に写る(どちらかのschemaファイル名を変更する)"
            )
        mapping[module] = schema_path
    return mapping


def generate_all(schemas_dir: Path, output_dir: Path) -> tuple[Path, ...]:
    """schemas/ 内の全schemaからモデルを生成し、書き込んだパスを返す。

    Raises:
        ValueError: schemaファイル名がモジュール名で衝突する(_module_mapping参照)。
    """
    mapping = _module_mapping(collect_schema_files(schemas_dir))
    output_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for module, schema_path in mapping.items():
        output_path = output_dir / module
        _generate_model(schema_path, output_path)
        written.append(output_path)
    return tuple(written)


def find_drift(schemas_dir: Path, models_dir: Path) -> tuple[str, ...]:
    """schemas/ から再生成した結果と models_dir を比較し、乖離の一覧を返す(空なら一致)。

    乖離の種類: missing(生成物が無い)/ stale(内容が古い)/ orphan(対応schemaが無い)。
    """
    with tempfile.TemporaryDirectory() as tmp:
        fresh_files = generate_all(schemas_dir, Path(tmp))
        drifts = []
        for fresh in fresh_files:
            committed = models_dir / fresh.name
            if not committed.is_file():
                drifts.append(f"missing: {committed}(未生成。再生成が必要)")
            elif committed.read_bytes() != fresh.read_bytes():
                drifts.append(f"stale: {committed}(schemasと不一致。再生成が必要)")
        expected_names = {f.name for f in fresh_files}
        drifts.extend(
            f"orphan: {path}(対応するschemaが無い。削除が必要)"
            for path in sorted(models_dir.glob("*.py"))
            if path.name not in expected_names and path.name != "__init__.py"
        )
        return tuple(drifts)


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="gen_models",
        description="schemas/*.schema.json から Pydanticモデル(models/)を生成する",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="書き込まず、コミット済み models/ が再生成結果と一致するかだけ検証する(CI用)",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(sys.argv[1:] if argv is None else argv)
    schemas_dir = _REPO_ROOT / "schemas"
    models_dir = _REPO_ROOT / "models"
    try:
        if args.check:
            drifts = find_drift(schemas_dir, models_dir)
            if drifts:
                for drift in drifts:
                    print(drift, file=sys.stderr)
                regen_hint = "check失敗: uv run python scripts/gen_models.py で再生成する"
                print(regen_hint, file=sys.stderr)
                return 1
            print(f"ok: {models_dir} は {schemas_dir} の再生成結果と一致")
            return 0
        for path in generate_all(schemas_dir, models_dir):
            print(f"wrote: {path}")
        return 0
    except (FileNotFoundError, ValueError, ModelGenerationError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
