#!/usr/bin/env python3
"""schemas/*.schema.json から Pydantic v2 モデル(models/)を生成する。

正本はJSON Schema(ADR-0002)。Pydanticモデルは単方向生成の生成物としてコミットし、
--check でCIが「再生成→diff無し」を検証する(乖離防止)。

生成はdatamodel-code-generatorのディレクトリ入力モードで一括実行する。各specは
allOf でartifact-baseを外部$ref参照する(modular reference)ため、ファイル単位の
--output指定はdcgが受け付けない(T-004)。モジュール名はdcgの命名規則
(artifact-base.schema.json → artifact_base_schema.py)に従い、継承は
`class RequirementSpec(ArtifactBase)` のようにモジュール間importへ写る。

使用例:
    uv run python scripts/gen_models.py          # models/ を再生成
    uv run python scripts/gen_models.py --check  # 差分検証のみ(CI用、書き込まない)
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

_SCHEMA_SUFFIX = ".schema.json"
_REPO_ROOT = Path(__file__).resolve().parent.parent
_INIT_MODULE = "__init__.py"


class ModelGenerationError(Exception):
    """モデル生成が失敗した(入力schema・stderr等の文脈を含む)。"""


def module_name_for(schema_filename: str) -> str:
    """schemaファイル名を生成モジュール名へ写す(dcgディレクトリ入力モードの命名規則。
    例: artifact-base.schema.json → artifact_base_schema.py)。

    Raises:
        ValueError: 命名規約(`<artifact-type>.schema.json`、schemas/README.md)に合わない。
    """
    if not schema_filename.endswith(_SCHEMA_SUFFIX):
        raise ValueError(f"schemaファイル名は *{_SCHEMA_SUFFIX} であること: {schema_filename}")
    stem = schema_filename.removesuffix(".json")
    return f"{stem.replace('-', '_').replace('.', '_')}.py"


def collect_schema_files(schemas_dir: Path) -> tuple[Path, ...]:
    """schemas/ から *.schema.json を名前順で集める(決定的)。

    Raises:
        FileNotFoundError: ディレクトリ欠落・schemaファイル0件。
    """
    if not schemas_dir.is_dir():
        raise FileNotFoundError(f"schemaディレクトリが存在しない: {schemas_dir}")
    files = sorted(schemas_dir.glob(f"*{_SCHEMA_SUFFIX}"))
    if not files:
        raise FileNotFoundError(f"schemaファイル(*{_SCHEMA_SUFFIX})が1件も無い: {schemas_dir}")
    return tuple(files)


def _validate_schema_json(schema_path: Path) -> None:
    """schemaを個別にJSON parseして事前検証する。

    dcgの一括実行はparse失敗時のエラーにファイル名を含めない(yamlパーサの素のエラーのみ)
    ため、ここでファイル名付きの文脈を確保する。
    """
    try:
        json.loads(schema_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise ModelGenerationError(
            f"schemaがJSONとしてparseできない: {schema_path.name}: {exc}"
        ) from exc


def _file_header() -> str:
    # dcg既定ヘッダは入力パス名(一時ディレクトリ名)を埋めて決定性を壊すため固定文言で置換する
    return (
        "# generated by scripts/gen_models.py from schemas/*.schema.json — do not edit\n"
        "# 正本はJSON Schema(ADR-0002)。再生成: uv run python scripts/gen_models.py"
    )


def _generator_cmd(input_dir: Path, output_dir: Path) -> tuple[str, ...]:
    return (
        sys.executable,
        "-m",
        "datamodel_code_generator",
        "--input",
        str(input_dir),
        "--input-file-type",
        "jsonschema",
        "--output",
        str(output_dir),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.12",
        # CI diff検証の前提となる決定的出力のため、timestampを消しformatterを固定する
        "--disable-timestamp",
        "--formatters",
        "black",
        "isort",
        # con*型ではなくFieldの制約で表現する(Pydantic v2の推奨スタイル)
        "--field-constraints",
        "--custom-file-header",
        _file_header(),
    )


def _run_generator(input_dir: Path, output_dir: Path) -> None:
    result = subprocess.run(
        _generator_cmd(input_dir, output_dir),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        # 診断はstderrが主だが、ツール側の出し先変更で手がかりを失わないようstdoutも残す
        details = "\n".join(part for part in (result.stderr.strip(), result.stdout.strip()) if part)
        raise ModelGenerationError(f"生成失敗: {input_dir} (exit {result.returncode})\n{details}")


def _module_mapping(schema_files: tuple[Path, ...]) -> dict[str, Path]:
    """モジュール名→schemaファイルの写像を作る。衝突は黙った上書きになるためfail-fastする。

    Raises:
        ValueError: 複数schemaが同一モジュール名に写る(例: a-b と a_b はともに a_b_schema.py)。
    """
    mapping: dict[str, Path] = {}
    for schema_path in schema_files:
        module = module_name_for(schema_path.name)
        if module in mapping:
            raise ValueError(
                f"モジュール名衝突: {mapping[module].name} と {schema_path.name} が"
                f"同じ {module} に写る(どちらかのschemaファイル名を変更する)"
            )
        mapping[module] = schema_path
    return mapping


def generate_all(schemas_dir: Path, output_dir: Path) -> tuple[Path, ...]:
    """schemas/ 内の全schemaから一括生成し、output_dir を生成結果と一致させる。

    models/ は全体が生成物のため、対応schemaを失った既存 *.py は削除する。

    Raises:
        ValueError: schemaファイル名がモジュール名で衝突する(_module_mapping参照)。
        ModelGenerationError: schemaのJSON parse失敗・dcg実行失敗・生成モジュール構成の不一致。
    """
    schema_files = collect_schema_files(schemas_dir)
    mapping = _module_mapping(schema_files)
    for schema_path in schema_files:
        _validate_schema_json(schema_path)
    expected = set(mapping) | {_INIT_MODULE}
    with tempfile.TemporaryDirectory() as tmp:
        tmp_in = Path(tmp) / "in"
        tmp_in.mkdir()
        tmp_out = Path(tmp) / "out"
        for schema_path in schema_files:
            shutil.copy(schema_path, tmp_in / schema_path.name)
        _run_generator(tmp_in, tmp_out)
        generated = {p.name for p in tmp_out.glob("*.py")}
        if generated != expected:
            raise ModelGenerationError(
                "生成モジュール構成が期待と一致しない(dcgの命名規則変更の可能性)。"
                f"期待: {sorted(expected)} / 実際: {sorted(generated)}"
            )
        output_dir.mkdir(parents=True, exist_ok=True)
        # 先に新規/更新を書き込み、orphan削除は最後に行う(copy途中の失敗で
        # 「削除済みなのに未書き込み」という中途半端な状態を残さないため)
        written = []
        for name in sorted(expected):
            target = output_dir / name
            shutil.copy(tmp_out / name, target)
            written.append(target)
        for orphan in output_dir.glob("*.py"):
            if orphan.name not in expected:
                orphan.unlink()
        return tuple(written)


def find_drift(schemas_dir: Path, models_dir: Path) -> tuple[str, ...]:
    """schemas/ から再生成した結果と models_dir を比較し、乖離の一覧を返す(空なら一致)。

    乖離の種類: missing(生成物が無い)/ stale(内容が古い)/ orphan(対応schemaが無い)。
    __init__.py も生成物として比較対象に含む。
    """
    with tempfile.TemporaryDirectory() as tmp:
        fresh_files = generate_all(schemas_dir, Path(tmp) / "models")
        drifts = []
        for fresh in fresh_files:
            committed = models_dir / fresh.name
            if not committed.is_file():
                drifts.append(f"missing: {committed}(未生成。再生成が必要)")
            elif committed.read_bytes() != fresh.read_bytes():
                drifts.append(f"stale: {committed}(schemasと不一致。再生成が必要)")
        expected_names = {f.name for f in fresh_files}
        drifts.extend(
            f"orphan: {path}(対応するschemaが無い。削除が必要)"
            for path in sorted(models_dir.glob("*.py"))
            if path.name not in expected_names
        )
        return tuple(drifts)


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="gen_models",
        description="schemas/*.schema.json から Pydanticモデル(models/)を生成する",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="書き込まず、コミット済み models/ が再生成結果と一致するかだけ検証する(CI用)",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(sys.argv[1:] if argv is None else argv)
    schemas_dir = _REPO_ROOT / "schemas"
    models_dir = _REPO_ROOT / "models"
    try:
        if args.check:
            drifts = find_drift(schemas_dir, models_dir)
            if drifts:
                for drift in drifts:
                    print(drift, file=sys.stderr)
                regen_hint = "check失敗: uv run python scripts/gen_models.py で再生成する"
                print(regen_hint, file=sys.stderr)
                return 1
            print(f"ok: {models_dir} は {schemas_dir} の再生成結果と一致")
            return 0
        for path in generate_all(schemas_dir, models_dir):
            print(f"wrote: {path}")
        return 0
    except (OSError, ValueError, ModelGenerationError) as exc:
        # OSErrorはFileNotFoundError(schemas/欠落)に加え、models/がファイルとして
        # 存在する場合のFileExistsError等も含む(生tracebackにせずexit 2へ正規化)
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
