# generated by scripts/gen_models.py from schemas/artifact-base.schema.json — do not edit
# 正本はJSON Schema(ADR-0002)。再生成: uv run python scripts/gen_models.py

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class CreatedBy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent: str = Field(..., min_length=1)
    skill: str = Field(..., min_length=1)
    model: str = Field(..., min_length=1)


class Status(StrEnum):
    draft = 'draft'
    reviewed = 'reviewed'
    approved = 'approved'
    deprecated = 'deprecated'


class ArtifactBase(BaseModel):
    artifact_id: str = Field(
        ..., description='artifactの一意識別子(例: REQ-001)', min_length=1
    )
    artifact_type: str = Field(
        ...,
        description='artifact種別。各artifact schemaが const で自身の型名に固定する',
        min_length=1,
    )
    version: str = Field(
        ...,
        description='artifact自体のバージョン(semver 2.0.0)',
        pattern='^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$',
    )
    source_refs: list[str] = Field(
        ...,
        description='根拠sourceへの参照。空のartifactはrelease gateに使えない(§6.1)ため、required(キー存在)に加え minItems: 1 で空配列をrejectする(ADR-0002)。item側のminLengthは付けない(datamodel-code-generatorがitem制約を名前付きRootModelに具象化し、生成モデルの値セマンティクスを壊すため。§6.1もitem制約は要求していない)',
        min_length=1,
    )
    created_by: CreatedBy = Field(..., description='生成主体(agent / skill / model)')
    confidence: float = Field(
        ...,
        description='自己申告confidence(0.0〜1.0)。gate条件の入力に使う場合は較正が必要(§6.1の注意書き)',
        ge=0.0,
        le=1.0,
    )
    status: Status = Field(..., description='artifactのライフサイクル状態')
    requires_human_review: bool = Field(..., description='人間レビューが必要か')
    trace_id: str = Field(
        ..., description='生成runのtrace識別子(§15。ID体系の設計はT-012)', min_length=1
    )
    created_at: AwareDatetime = Field(
        ...,
        description='生成時刻(RFC 3339 date-time。timezone必須が契約意図)。生成PydanticモデルはAwareDatetimeでtimezoneを強制済み。formatはdraft 2020-12では注釈のため生JSON検証では強制されず、生JSON側で強制するかはvalidator(T-008)で決める',
    )
