# generated by scripts/gen_models.py from schemas/*.schema.json — do not edit
# 正本はJSON Schema(ADR-0002)。再生成: uv run python scripts/gen_models.py

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .artifact_base_schema import ArtifactBase


class ChangeType(StrEnum):
    added = 'added'
    modified = 'modified'
    deleted = 'deleted'
    renamed = 'renamed'


class RiskLevel(StrEnum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    critical = 'critical'


class ChangedFile(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    path: str = Field(..., description='変更されたファイルpath', min_length=1)
    change_type: ChangeType = Field(..., description='PR diff上の変更種別')
    risk_level: RiskLevel = Field(
        ...,
        description='ファイル変更単位の暫定リスク。値域はRiskSpec.severityと同じ4段階',
    )


class ChangeImpactSpec(ArtifactBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_type: Literal['change_impact_spec'] = Field(
        ..., description='artifact種別(§6.1の規約により const で固定)'
    )
    change_impact_id: str = Field(
        ..., description='ChangeImpactSpecのdomain識別子(例: CIS-PR-123)', min_length=1
    )
    changed_files: list[ChangedFile] = Field(
        ...,
        description='PR diffで変更されたファイル。ChangeImpactSpecはPR差分に対して作るため最低1件必要',
        min_length=1,
    )
    changed_components: list[str] = Field(
        ..., description='変更により影響を受けるcomponent。§21 Week 1 DoD', min_length=1
    )
    impacted_requirements: list[str] = Field(
        ...,
        description='影響を受けるRequirementSpec.req_id。Phase 0 generator(T-010)では候補レベルのため、空配列は分析済みだがマッピング未収集または該当なしを表す',
    )
    impacted_risks: list[str] = Field(
        ...,
        description='影響を受けるRiskSpec.risk_id。Phase 0 generator(T-010)では候補レベルのため、空配列は分析済みだがマッピング未収集または該当なしを表す',
    )
    impacted_apis: list[str] = Field(
        ...,
        description='影響を受けるAPI。API影響ゼロの変更もあり得るため、空配列は分析済みだがマッピング未収集または該当なしを表す',
    )
    impacted_state_models: list[str] | None = Field(
        None, description='影響を受けるstate model。無い場合はキー省略', min_length=1
    )
    impacted_existing_tests: list[str] | None = Field(
        None, description='影響を受ける既存TestAsset。無い場合はキー省略', min_length=1
    )
