# generated by scripts/gen_models.py from schemas/*.schema.json — do not edit
# 正本はJSON Schema(ADR-0002)。再生成: uv run python scripts/gen_models.py

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from .artifact_base_schema import ArtifactBase


class Environment(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    env_id: str = Field(
        ..., description='実行環境の識別子(例: sandbox-789)', min_length=1
    )
    seed: str | None = Field(
        None, description='fixture / seedへの参照または識別子', min_length=1
    )
    clock: AwareDatetime | None = Field(
        None, description='実行時に固定したclock(RFC 3339 date-time)'
    )


class Status(StrEnum):
    success = 'success'
    failure = 'failure'
    skipped = 'skipped'
    timeout = 'timeout'


class ToolCall(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    name: str = Field(..., description='tool名', min_length=1)
    status: Status = Field(..., description='tool call結果')


class Kind(StrEnum):
    app = 'app'
    test_runner = 'test_runner'
    tool = 'tool'
    system = 'system'
    other = 'other'


class Log(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ref: str = Field(..., description='redacted log保存先への参照', min_length=1)
    kind: Kind | None = Field(None, description='log種別(§15.3 logs)')


class Screenshot(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ref: str = Field(..., description='screenshot/video保存先への参照', min_length=1)
    kind: str | None = Field(
        None, description='capture種別(例: ui / video / trace)', min_length=1
    )


class Verdict(StrEnum):
    pass_ = 'pass'
    fail = 'fail'
    inconclusive = 'inconclusive'


class GraderResult(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    verdict: Verdict = Field(..., description='grader単位の判定')
    score: float | None = Field(
        None, description='grader score(0.0〜1.0)', ge=0.0, le=1.0
    )
    confidence: float | None = Field(
        None, description='grader confidence(0.0〜1.0)', ge=0.0, le=1.0
    )


class ExecutionEvidence(ArtifactBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_type: Literal['execution_evidence'] = Field(
        ..., description='artifact種別(§6.1の規約により const で固定)'
    )
    run_id: str = Field(
        ..., description='実行runの識別子(例: RUN-20260630-001)', min_length=1
    )
    test_asset_id: str = Field(
        ...,
        description='実行対象TestAssetへの参照(例: TEST-ORDER-CANCEL-001)',
        min_length=1,
    )
    environment: Environment = Field(
        ...,
        description='実行環境metadata。環境ごとに必要な追加metadataが異なるため開いておく',
    )
    inputs: dict[str, Any] = Field(
        ...,
        description='test input / fixture / seed等の保存参照またはredacted metadata(§15.3 input)。shapeは実行対象ごとに異なるため開いておく',
    )
    outputs: dict[str, Any] = Field(
        ...,
        description='test実行結果、response、UI screenshot、API response等の保存参照またはredacted metadata(§15.3 output)。shapeは実行対象ごとに異なるため開いておく',
    )
    state_before: dict[str, Any] = Field(
        ...,
        description='DB snapshot/hash、event queue、audit log等の実行前状態参照(§15.3 state before)',
    )
    state_after: dict[str, Any] = Field(
        ...,
        description='DB snapshot/hash、event queue、audit log等の実行後状態参照(§15.3 state after)',
    )
    state_diff: dict[str, Any] = Field(
        ...,
        description='実行前後の変更差分または差分保存先への参照(§6.23 / §15.3 state diff)',
    )
    tool_calls: list[ToolCall] = Field(
        ...,
        description='tool call履歴(§6.23)。tool callが無い実行もあるため空配列を許す',
    )
    logs: list[Log] = Field(
        ...,
        description='app log、test runner log等への参照(§15.3 logs)。logが無い実行もあるため空配列を許す',
    )
    screenshots: list[Screenshot] = Field(
        ...,
        description='UI/E2E時のscreenshot/video参照(§15.3)。UIが無い実行もあるため空配列を許す',
    )
    grader_results: list[GraderResult] = Field(
        ...,
        description='grader result(§15.3)。graderを使わない実行もあるため空配列を許す',
    )
    verdict: Verdict = Field(..., description='ExecutionEvidence全体の判定(§6.23)')
    reproduction_bundle: str = Field(
        ...,
        description='再実行手順、test data、environment metadataをまとめたbundleへの参照(§15.3 reproduction bundle)',
        min_length=1,
    )
