# generated by scripts/gen_models.py from schemas/*.schema.json — do not edit
# 正本はJSON Schema(ADR-0002)。再生成: uv run python scripts/gen_models.py

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .artifact_base_schema import ArtifactBase


class OracleTypeEnum(StrEnum):
    exact = 'exact'
    state = 'state'
    contract = 'contract'
    invariant = 'invariant'
    differential = 'differential'
    metamorphic = 'metamorphic'
    statistical = 'statistical'
    model_judge = 'model_judge'
    human = 'human'


class Signal(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: str = Field(
        ...,
        description='観測点の種別(例: db / api / event / audit_log / ui。§6.5 observation_points参照)。種別ごとにsignalの形が異なる(query_ref / endpoint / topic等)ため語彙も追加fieldも開いておく',
        min_length=1,
    )


class OracleSpec(ArtifactBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_type: Literal['oracle_spec'] = Field(
        ..., description='artifact種別(§6.1の規約により const で固定)'
    )
    oracle_id: str = Field(
        ...,
        description='oracleのdomain識別子(例: ORACLE-ORDER-CANCEL-001)',
        min_length=1,
    )
    req_refs: list[str] = Field(
        ...,
        description='対象要求(RequirementSpec.req_id)への参照。oracle-first(§9.1)によりOracleSpecは要求ごとに作るため最低1件必要',
        min_length=1,
    )
    risk_refs: list[str] | None = Field(
        None,
        description='対象リスク(RiskSpec.risk_id)への参照。無い場合はキー省略(空配列は不可)',
        min_length=1,
    )
    oracle_type: list[OracleTypeEnum] = Field(
        ...,
        description='oracle種別。値域は§9.2 Oracle分類 + §9.3のmodel judge。生成Pydanticモデルではitemsのenumが名前付きEnum化される(意図的。string値は .value で取る)。uniqueItemsは生JSON検証でのみ強制され、生成モデルへは変換されない(既知の非対称。regression testで挙動を固定済み)',
        min_length=1,
    )
    signals: list[Signal] = Field(
        ...,
        description='pass判定に使う観測signal。観測せずに判定できるoracleは無いため最低1件必要',
        min_length=1,
    )
    pass_condition: str = Field(
        ...,
        description='pass判定条件の記述(例: all required state changes observed)',
        min_length=1,
    )
    human_review_required_if: list[str] | None = Field(
        None,
        description='人間レビューへエスカレーションする条件。無い場合はキー省略(空配列は不可)',
        min_length=1,
    )
