# generated by scripts/gen_models.py from schemas/*.schema.json — do not edit
# 正本はJSON Schema(ADR-0002)。再生成: uv run python scripts/gen_models.py

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from .artifact_base_schema import ArtifactBase


class TimeWindow(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    from_: AwareDatetime | None = Field(
        None, alias='from', description='集計開始時刻(RFC 3339 date-time)'
    )
    to: AwareDatetime | None = Field(
        None, description='集計終了時刻(RFC 3339 date-time)'
    )


class Scope(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    release_candidate: str | None = Field(
        None, description='snapshot対象のrelease candidate', min_length=1
    )
    branch: str | None = Field(None, description='snapshot対象branch', min_length=1)
    time_window: TimeWindow | None = Field(
        None, description='集計期間。運用側のwindow label等を追加できる'
    )


class Coverage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    requirement_coverage: float | None = Field(
        None,
        description='要求coverage比率(0.0〜1.0)。未収集の場合はnull',
        ge=0.0,
        le=1.0,
    )
    risk_coverage: float | None = Field(
        None,
        description='risk coverage比率(0.0〜1.0)。未収集の場合はnull',
        ge=0.0,
        le=1.0,
    )
    oracle_definition_rate: float | None = Field(
        None, description='oracle定義率(0.0〜1.0)。未収集の場合はnull', ge=0.0, le=1.0
    )
    evidence_completeness: float | None = Field(
        None,
        description='evidence completeness比率(0.0〜1.0)。未収集の場合はnull',
        ge=0.0,
        le=1.0,
    )


class Execution(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    total_tests: int | None = Field(
        None, description='実行対象テスト総数。未収集の場合はnull', ge=0
    )
    selected_tests: int | None = Field(
        None, description='選択実行されたテスト数。未収集の場合はnull', ge=0
    )
    passed: int | None = Field(None, description='pass件数。未収集の場合はnull', ge=0)
    failed: int | None = Field(None, description='fail件数。未収集の場合はnull', ge=0)
    inconclusive: int | None = Field(
        None, description='inconclusive件数。未収集の場合はnull', ge=0
    )
    flaky_suspected: int | None = Field(
        None, description='flake疑い件数。未収集の場合はnull', ge=0
    )


class QualityIntelligence(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    impacted_requirements: int | None = Field(
        None, description='影響要求数。未収集の場合はnull', ge=0
    )
    coverage_gaps: int | None = Field(
        None, description='coverage gap数。未収集の場合はnull', ge=0
    )
    untested_changes: int | None = Field(
        None, description='未テスト変更数。未収集の場合はnull', ge=0
    )
    high_risk_untested_changes: int | None = Field(
        None, description='高リスク未テスト変更数。未収集の場合はnull', ge=0
    )


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    evidence_refs: list[str] | None = Field(
        None,
        description='集計元Evidence / runへの参照。Phase 0では未収集を空配列で表せる',
    )
    evidence_count: int | None = Field(
        None, description='集計したevidence件数。未収集の場合はnull', ge=0
    )
    missing_evidence_count: int | None = Field(
        None, description='不足evidence件数。未収集の場合はnull', ge=0
    )


class Cost(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    llm_cost_usd: float | None = Field(
        None, description='LLM cost(USD)。未収集の場合はnull', ge=0.0
    )
    test_runtime_minutes: float | None = Field(
        None, description='テスト実行時間(分)。未収集の場合はnull', ge=0.0
    )
    cost_per_detected_defect: float | None = Field(
        None,
        description='検出defectあたりcost。未収集またはdefectなしの場合はnull',
        ge=0.0,
    )


class QualityAnalyticsSnapshot(ArtifactBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_type: Literal['quality_analytics_snapshot'] = Field(
        ..., description='artifact種別(§6.1の規約により const で固定)'
    )
    snapshot_id: str = Field(
        ...,
        description='QualityAnalyticsSnapshotのdomain識別子(例: QAS-20260630-001)',
        min_length=1,
    )
    scope: Scope = Field(
        ...,
        description='snapshot対象範囲。repo種別やrelease管理systemごとの追加metadataを許す',
    )
    coverage: Coverage = Field(
        ...,
        description='coverage集約bucket。Phase 0ではproducer未定義のため個別metricは必須化しない',
    )
    execution: Execution = Field(
        ..., description='execution結果集約bucket。未収集metricは省略またはnullで表す'
    )
    quality_intelligence: QualityIntelligence | None = Field(
        None,
        description='Quality Intelligenceの補助集約。§6.17サンプルに合わせるが、T-007 DoDの必須bucketではないためoptional',
    )
    evidence: Evidence = Field(
        ...,
        description='evidence集約bucket。source_refsとは別に集計元runやEvidence Store参照を保持する。§6.17からのPhase 0構造逸脱であり、理由はdocs/knowledge/learning-log.md 2026-07-03 entryに記録',
    )
    cost: Cost = Field(
        ..., description='cost集約bucket。未収集metricは省略またはnullで表す'
    )
