# generated by scripts/gen_models.py from schemas/*.schema.json — do not edit
# 正本はJSON Schema(ADR-0002)。再生成: uv run python scripts/gen_models.py

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .artifact_base_schema import ArtifactBase


class DecisionRecommendation(StrEnum):
    pass_ = 'pass'
    warn = 'warn'
    block = 'block'


class CoverageSummary(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    p0_p1_source_grounding: float | None = Field(
        None,
        description='P0/P1 source grounding率(0.0〜1.0)。未収集の場合はnull',
        ge=0.0,
        le=1.0,
    )
    p0_p1_oracle_definition: float | None = Field(
        None,
        description='P0/P1 oracle定義率(0.0〜1.0)。未収集の場合はnull',
        ge=0.0,
        le=1.0,
    )
    risk_coverage: float | None = Field(
        None,
        description='risk coverage率(0.0〜1.0)。未収集の場合はnull',
        ge=0.0,
        le=1.0,
    )
    evidence_completeness: float | None = Field(
        None,
        description='evidence completeness率(0.0〜1.0)。未収集の場合はnull',
        ge=0.0,
        le=1.0,
    )


class QualityIntelligenceSummary(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    untested_changes: int | None = Field(
        None, description='未テスト変更数。未収集の場合はnull', ge=0
    )
    coverage_gaps: int | None = Field(
        None, description='coverage gap数。未収集の場合はnull', ge=0
    )
    recommended_followups: list[str] | None = Field(
        None, description='推奨follow-up。無い場合は空配列'
    )


class Reason(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    reason: str = Field(..., description='block / warn の理由本文', min_length=1)
    requirement_ref: str | None = Field(
        None, description='関連RequirementSpecへの参照', min_length=1
    )
    risk_ref: str | None = Field(None, description='関連RiskSpecへの参照', min_length=1)
    evidence_refs: list[str] | None = Field(
        None, description='この理由を支えるEvidence / runへの参照。未収集の場合は空配列'
    )


class ReleaseReadinessReport(ArtifactBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_type: Literal['release_readiness_report'] = Field(
        ..., description='artifact種別(§6.1の規約により const で固定)'
    )
    report_id: str = Field(
        ...,
        description='ReleaseReadinessReportのdomain識別子(例: RRR-20260630-001)',
        min_length=1,
    )
    release_candidate: str = Field(
        ..., description='readiness判定対象のrelease candidate', min_length=1
    )
    decision_recommendation: DecisionRecommendation = Field(
        ..., description='release候補への推奨判定'
    )
    readiness_score: float | None = Field(
        None,
        description='readiness score(0.0〜1.0)。未収集の場合はnull',
        ge=0.0,
        le=1.0,
    )
    blocking_reasons: list[Reason] = Field(
        ..., description='block理由。pass / warnでは空配列を許す'
    )
    warning_reasons: list[Reason] = Field(
        ..., description='warn理由。pass / blockでは空配列を許す'
    )
    coverage_summary: CoverageSummary | None = Field(
        None, description='coverage系の要約。Phase 0ではproducer未定義のためoptional'
    )
    quality_intelligence_summary: QualityIntelligenceSummary | None = Field(
        None, description='Quality Intelligenceの要約。運用metric追加を許す'
    )
    human_review_required: bool | None = Field(
        None,
        description='このreportのdomain判定として人間レビューが必要か。ArtifactBase.requires_human_reviewとは別に、release判断上の要否を表すoptional field',
    )
    required_approvers: list[str] | None = Field(
        None, description='必要承認者role。未確定または不要なら空配列'
    )
    analytics_snapshot_ref: str | None = Field(
        None, description='参照したQualityAnalyticsSnapshotのsnapshot_id', min_length=1
    )
    residual_risk_report_ref: str | None = Field(
        None, description='参照したResidualRiskReportのID', min_length=1
    )
    evidence_refs: list[str] = Field(
        ...,
        description='report全体の判定を支えるEvidence / snapshotへの参照。Phase 0では空配列を許す',
    )
