# generated by scripts/gen_models.py from schemas/*.schema.json — do not edit
# 正本はJSON Schema(ADR-0002)。再生成: uv run python scripts/gen_models.py

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import ConfigDict, Field

from .artifact_base_schema import ArtifactBase


class BusinessImpact(StrEnum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    critical = 'critical'


class RequirementSpec(ArtifactBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_type: Literal['requirement_spec'] = Field(
        ..., description='artifact種別(§6.1の規約により const で固定)'
    )
    req_id: str = Field(
        ...,
        description='要求のdomain識別子(例: REQ-ORDER-CANCEL-001)。OracleSpec.req_refs等の参照キー',
        min_length=1,
    )
    title: str = Field(..., description='要求の短い表題', min_length=1)
    description: str | None = Field(
        None,
        description='要求の説明。抽出時点で書けないことがあるためoptional',
        min_length=1,
    )
    acceptance_criteria: list[str] = Field(
        ...,
        description='受け入れ条件。oracle設計(§9)の入力になるため最低1件必要。item側の制約は付けない(artifact-base.schema.json の source_refs と同じ生成器都合)',
        min_length=1,
    )
    business_impact: BusinessImpact | None = Field(
        None,
        description='ビジネス影響度。値域はNorth Starに列挙がないため実装で確定した4段階(severityと同尺度。§6.3の用例 high / §8.4の critical 比較を被覆)',
    )
    owner: str | None = Field(
        None, description='要求のオーナー(チーム等)', min_length=1
    )
