# generated by scripts/gen_models.py from schemas/*.schema.json — do not edit
# 正本はJSON Schema(ADR-0002)。再生成: uv run python scripts/gen_models.py

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import ConfigDict, Field

from .artifact_base_schema import ArtifactBase


class Severity(StrEnum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    critical = 'critical'


class Likelihood(StrEnum):
    low = 'low'
    medium = 'medium'
    high = 'high'


class Detectability(StrEnum):
    low = 'low'
    medium = 'medium'
    high = 'high'


class RiskSpec(ArtifactBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_type: Literal['risk_spec'] = Field(
        ..., description='artifact種別(§6.1の規約により const で固定)'
    )
    risk_id: str = Field(
        ...,
        description='リスクのdomain識別子(例: RISK-BILLING-001)。OracleSpec.risk_refs等の参照キー',
        min_length=1,
    )
    title: str = Field(..., description='リスクの短い表題', min_length=1)
    severity: Severity = Field(
        ...,
        description='影響の深刻度。値域はNorth Starに列挙がないため実装で確定した4段階(§6.4 critical / §6.11 high / §8.4 gate条件 critical の用例を被覆)',
    )
    likelihood: Likelihood = Field(
        ...,
        description='発生しやすさ。severityと違い critical は意味を成さないため3段階',
    )
    detectability: Detectability | None = Field(
        None,
        description='検出しやすさ(FMEAの第3軸)。評価できない段階があるためoptional',
    )
    risk_type: str | None = Field(
        None,
        description='リスク種別(例: financial / security / privacy)。一般リスクの語彙はNorth Starで固定されていないため開いたstring(性能リスクは§6.19 PerformanceRiskSpecが別schemaで独自enumを持つ)',
        min_length=1,
    )
    past_incident_refs: list[str] | None = Field(
        None,
        description='過去incidentへの参照。無い場合はキー省略(空配列は不可)',
        min_length=1,
    )
    mitigation: str | None = Field(None, description='緩和策の記述', min_length=1)
