# generated by scripts/gen_models.py from schemas/*.schema.json — do not edit
# 正本はJSON Schema(ADR-0002)。再生成: uv run python scripts/gen_models.py

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from .artifact_base_schema import ArtifactBase


class Scope(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    repository: str = Field(..., description='index対象repository', min_length=1)
    branch: str = Field(..., description='index対象branch', min_length=1)


class TestType(StrEnum):
    unit = 'unit'
    integration = 'integration'
    api = 'api'
    e2e = 'e2e'
    ui = 'ui'
    contract = 'contract'
    performance = 'performance'
    security = 'security'
    manual = 'manual'
    other = 'other'


class Stability(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    flake_rate: float | None = Field(
        ...,
        description='flake rate(0.0〜1.0)。Phase 0 generator(T-009)で未収集の場合はnull',
        ge=0.0,
        le=1.0,
    )
    last_failed_at: AwareDatetime | None = Field(
        None, description='直近失敗時刻。未失敗または不明ならnull'
    )
    last_passed_at: AwareDatetime | None = Field(
        None, description='直近成功時刻。未成功または不明ならnull'
    )


class MaintenanceCost(StrEnum):
    low = 'low'
    medium = 'medium'
    high = 'high'


class Maintenance(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    owner: str | None = Field(None, description='保守owner', min_length=1)
    last_modified: date | None = Field(None, description='直近変更日')
    maintenance_cost: MaintenanceCost | None = Field(
        None, description='保守コストの概算'
    )


class Asset(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    test_id: str = Field(
        ...,
        description='既存テスト資産の識別子(例: TEST-API-ORDER-CANCEL-001)',
        min_length=1,
    )
    test_type: TestType = Field(
        ...,
        description='テスト種別。§6.13の api に加え、既存テスト資産として扱う代表的な種別',
    )
    path: str = Field(..., description='対象repo内のテストファイルpath', min_length=1)
    covered_requirements: list[str] = Field(
        ...,
        description='このテストがcoveredするRequirementSpec.req_id。Phase 0 generator(T-009)では未収集になり得るため、空配列はマッピング未収集または該当なしを表す',
    )
    covered_risks: list[str] = Field(
        ...,
        description='このテストがcoveredするRiskSpec.risk_id。Phase 0 generator(T-009)では未収集になり得るため、空配列はマッピング未収集または該当なしを表す',
    )
    covered_apis: list[str] | None = Field(
        None, description='このテストがcoveredするAPI。無い場合はキー省略', min_length=1
    )
    covered_state_models: list[str] | None = Field(
        None,
        description='このテストがcoveredするstate model。無い場合はキー省略',
        min_length=1,
    )
    oracle_refs: list[str] = Field(
        ...,
        description='このテストが対応するOracleSpec.oracle_id。Phase 0 generator(T-009)では未収集になり得るため、空配列はマッピング未収集または該当なしを表す',
    )
    stability: Stability = Field(
        ..., description='テスト安定性metadata。runnerごとの追加指標を許す'
    )
    maintenance: Maintenance | None = Field(
        None, description='保守metadata。確定しない場合はキー省略'
    )


class TestAssetIndex(ArtifactBase):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_type: Literal['test_asset_index'] = Field(
        ..., description='artifact種別(§6.1の規約により const で固定)'
    )
    index_id: str = Field(
        ..., description='TestAssetIndexのdomain識別子(例: TAI-ORDER-001)', min_length=1
    )
    indexed_at: AwareDatetime = Field(
        ..., description='index生成時刻(RFC 3339 date-time)'
    )
    scope: Scope = Field(
        ..., description='index対象範囲。repo種別やrunnerごとの追加metadataを許す'
    )
    assets: list[Asset] = Field(
        ...,
        description='既存テスト資産の一覧。対象repoにテストが無い状態も明示できるよう空配列を許す',
    )
